### ISSUE TITLE
go mod error

### ISSUE THREAD

**Issue by sodul** [christopherhein/go-version#16]
When we try to install aws-iam-authenticator with gobin we get this error which seems to be caused by an incorrect `go.mod` file:

```
github.com/christopherhein/go-version@v0.1.0: parsing go.mod: unexpected module path "go.hein.dev/go-version"
```

We suspect that the first line of the file should be:
`module  github.com/christopherhein/go-version`
 and not:
`module go.hein.dev/go-version`

**Comment by christopherhein** [comment]
This was put in to fix this https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/255 but it's yet to be merged :)
