### ISSUE TITLE
ToShortened() doesn't shorten the version

### ISSUE THREAD

**Issue by hofnarwillie** [christopherhein/go-version#30]
### Expected behaviour:

When running the version command with the `--short` flag it should only print the version. For example:

```
$ ./test.exe version --short
0.0.2-unstable
```

### Actual behaviour

The output is switched to yaml instead of printing a short version.

```
$ ./test.exe version --short
Commit: 59ae90ea5fa7aadf988852db5ce9a92253e1c774
Date: "2021-06-14T20:20:15Z"
Version: 0.0.2-unstable
```

I believe this function (ToShortened) should be modified:

https://github.com/christopherhein/go-version/blob/8d8724bf69d54e756d05655168211d60c0f55f7e/version.go#L71

**Comment by christopherhein** [comment]
Yea, this makes more sense especially since we have `.ToYAML()`. This PR apparently fixes it. Just waiting on me to merge, sorry about that. https://github.com/christopherhein/go-version/pull/29

**Comment by christopherhein** [comment]
If you use the latest `master` this change is reflected. I'll build a `v0.1.1` this week.

**Comment by hofnarwillie** [comment]
Thank you very much that was a super quick turn around!
